version: "3.8"
services:
  # db:
  #   container_name: postgres_container
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: database
  #   ports:
  #     - "5434:5432"
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 1234
  #   ports:
  #     - "5050:80"
  wealthfarming:
    build:
      context: .  # Chỉ định thư mục chứa Dockerfile của bạn
    container_name: wealthfarming
    ports:
      - "3000:3000"  # Mở cổng 3000 để có thể truy cập vào Next.js từ bên trong container
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.wealthfarming.entrypoints=http'
      - 'traefik.http.routers.wealthfarming.rule=Host(`wf.wealthfarming.org`)'
      - 'traefik.http.routers.wealthfarming-secure.entrypoints=https'
      - 'traefik.http.routers.wealthfarming-secure.rule=Host(`wf.wealthfarming.org`)'
      - 'traefik.http.routers.wealthfarming-secure.tls.certresolver=letsencrypt'

    networks:
      - traefik  # Kết nối container Next.js với network traefik

networks:
  traefik:
    external: true  # Đảm bảo Traefik và các dịch vụ container sử dụng cùng mạng này