/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    accounts: Account;
    'news-categories': NewsCategory;
    news: News;
    address: Address;
    banks: Bank;
    users: User;
    media: Media;
    companies: Company;
    'investment-funds': InvestmentFund;
    'investment-products': InvestmentProduct;
    contracts: Contract;
    transactions: Transaction;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsSelect?: {
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    address: AddressSelect<false> | AddressSelect<true>;
    banks: BanksSelect<false> | BanksSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'investment-funds': InvestmentFundsSelect<false> | InvestmentFundsSelect<true>;
    'investment-products': InvestmentProductsSelect<false> | InvestmentProductsSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect?: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs?: {
    tasks: unknown;
    workflows?: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  user: number | User;
  account_name: string;
  account_number: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'individual' | 'company';
  first_name?: string | null;
  last_name?: string | null;
  company_name?: string | null;
  registration_number?: string | null;
  phone_contact?: string | null;
  date_of_birth?: string | null;
  email_verified?: boolean | null;
  verification_token?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  category?: (number | null) | NewsCategory;
  user?: (number | null) | User;
  title?: string | null;
  content?: string | null;
  published_date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "address".
 */
export interface Address {
  id: number;
  user: number | User;
  street?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks".
 */
export interface Bank {
  id: number;
  user?: (number | null) | User;
  name?: string | null;
  account_number?: string | null;
  bank_name?: string | null;
  branch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  registration_number?: string | null;
  address?: string | null;
  contact_person: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-funds".
 */
export interface InvestmentFund {
  id: number;
  name: string;
  description?: string | null;
  category?: string | null;
  start_date: string;
  end_date: string;
  interest_rate: number;
  min_investment: number;
  max_investment?: number | null;
  fund_manager: number | User;
  status: 'active' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-products".
 */
export interface InvestmentProduct {
  id: number;
  fund: number | InvestmentFund;
  product_name: string;
  description?: string | null;
  min_investment: number;
  max_investment?: number | null;
  interest_rate_from: number;
  interest_rate_to: number;
  profit_period: 'monthly' | 'quarterly' | 'semi_annually' | 'annually';
  status: 'available' | 'unavailable';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  product_id: number | InvestmentProduct;
  account_id: number | Account;
  status: 'active' | 'inactive' | 'pending' | 'closed';
  amount: number;
  created_at?: string | null;
  updated_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  contract_id: number | Contract;
  amount: number;
  status: 'pending' | 'completed' | 'failed';
  from_account?: (number | null) | Account;
  to_account?: (number | null) | Account;
  type: 'deposit' | 'withdraw' | 'bonus' | 'manage_fee';
  created_at?: string | null;
  updated_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'address';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'banks';
        value: number | Bank;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'investment-funds';
        value: number | InvestmentFund;
      } | null)
    | ({
        relationTo: 'investment-products';
        value: number | InvestmentProduct;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  user?: T;
  account_name?: T;
  account_number?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  category?: T;
  user?: T;
  title?: T;
  content?: T;
  published_date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "address_select".
 */
export interface AddressSelect<T extends boolean = true> {
  user?: T;
  street?: T;
  city?: T;
  state?: T;
  zip_code?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks_select".
 */
export interface BanksSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  account_number?: T;
  bank_name?: T;
  branch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  first_name?: T;
  last_name?: T;
  company_name?: T;
  registration_number?: T;
  phone_contact?: T;
  date_of_birth?: T;
  email_verified?: T;
  verification_token?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  registration_number?: T;
  address?: T;
  contact_person?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-funds_select".
 */
export interface InvestmentFundsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  start_date?: T;
  end_date?: T;
  interest_rate?: T;
  min_investment?: T;
  max_investment?: T;
  fund_manager?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investment-products_select".
 */
export interface InvestmentProductsSelect<T extends boolean = true> {
  fund?: T;
  product_name?: T;
  description?: T;
  min_investment?: T;
  max_investment?: T;
  interest_rate_from?: T;
  interest_rate_to?: T;
  profit_period?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  product_id?: T;
  account_id?: T;
  status?: T;
  amount?: T;
  created_at?: T;
  updated_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  contract_id?: T;
  amount?: T;
  status?: T;
  from_account?: T;
  to_account?: T;
  type?: T;
  created_at?: T;
  updated_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  site_name: string;
  support_email: string;
  support_phone?: string | null;
  contact_address?: string | null;
  social_links?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  business_hours?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  navigationLinks?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contactInfo?: string | null;
  socialMediaLinks?:
    | {
        platform: string;
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyrightText: string;
  privacyPolicyLink?: string | null;
  aboutUsLink?: string | null;
  socialMediaLinks?:
    | {
        platform: string;
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  site_name?: T;
  support_email?: T;
  support_phone?: T;
  contact_address?: T;
  social_links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  business_hours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigationLinks?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  contactInfo?: T;
  socialMediaLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  privacyPolicyLink?: T;
  aboutUsLink?: T;
  socialMediaLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}