name: CICD

on:
  push:
    branches:
      - development
    paths-ignore:
      - '.vscode/**'
      - '.env*'
      - 'docs/**'
      - '**.md'

env:
  SERVICE: dev-wealthfarming

jobs:
  build-image:
    if: contains(github.event.head_commit.message, '[cd-skip]') == false
    runs-on: dev-wealthfarming
    steps:
      - uses: actions/checkout@v4
      - name: Check out repo
        run: docker build . --file Dockerfile --tag dev-wealthfarming:latest
  deploy:
  deploy:
    environment: development
    needs:
      - build-image
    runs-on: dev-wealthfarming
    steps:
      - run: |
          docker compose -f /root/wealthfarming/apps/docker-compose.yml up -d --force-recreate dev-wealthfarming
          docker image prune -f