name: CICD

on:
  push:
    branches:
      - development
    paths-ignore:
      - '.vscode/**'
      - '.env*'
      - 'docs/**'
      - '**.md'

env:
  SERVICE: dev-wf

jobs:
  build-image:
    if: contains(github.event.head_commit.message, '[cd-skip]') == false
    runs-on: dev-wf
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag dev-wf:latest

  deploy:
    needs: build-image
    runs-on: dev-wf
    container:
      image: dev-wf
      volumes:
        - '/root/wealth-farming/development/.env:/root/wealth-farming/apps/.env'
    steps:
      - name: Deploy Service
        run: |
          docker compose -f /root/wealth-farming/apps/docker-compose.yml up -d --force-recreate dev-wf
          docker image prune -f
